jabardigitalservice/portal-jabar-frontend

Dockerfile

Axios configuration for base url in `nuxt.config.js` file was not set correctly because axios can't read environment variables during the build process. Instead, localhost was used as a fallback.
- Update dockerfile

Fix axios environment variable not set correctly in docker file

---

components/Breadcrumb/index.vue

The default behavior of the `Breadcrumb` component is to render a list of routes based on the current browser route using `$route.path` . However, this is not always the desired behavior, sometimes we want a custom list of breadcrumb paths and item labels, so it makes sense to add an `items` prop to handle this scenario.
- add `items` props
- adjust object property name
- remove `capitalize` style when `items` props is defined

Improve Breadcrumb Component

---

components/News/index.vue

- Currently, there is an error in the backend API service, so every network request is returned with 500. This causes the site to crash because I forgot to add a `try catch` block 😢 
- I forgot to rename the `NewsHighlight` component after the merge conflict before this PR
title: Fix news page fetch error
participants: @Ibwedagama @maulanayuseph @naufalihsank

Fix: news page fetch error and fix component name

---

components/Carousel/index.vue
components/News/Header/index.vue

- [S18A2 - Berita Terkait](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recjdGUPSt5yLOSVk?blocks=hide)
- Add new props to carousel component to disable default hover
- Create related news widget
Title: Add related news widget
Participants: @bangunbagustapa @adzharamrullah @naufalihsank @maruf12 @Ibwedagama

Feat: related news

---

components/Carousel/index.vue
components/Hero/Image/index.vue
components/LatestNews/Preview/index.vue
components/News/Header/index.vue

There's an issue with [keen-slider](https://keen-slider.io/) when it renders in the client-side. The library isn't working well with hybrid rendering.
Why not use another library instead? Most slider / carousel library for Vue.js work for client-side rendering, there's a few library that support server-side rendering, like [keen-slider](https://keen-slider.io/) but not hybrid rendering.
We create our own simple carousel to provide both client-side rendering and server-side rendering. These change spesific for our current use case.
- Create carousel component
- Replace all component that used old carousel to the new one
Title: Remove keen slider for carousel and create our own carouse component
Participants: @bangunbagustapa @Ibwedagama @adzharamrullah @naufalihsank

Remove keen slider for carousel and create our own carouse component

---

components/Agenda/Navigation/index.vue

- [T23 - Kalendar Mingguan - Range tanggal diantara 2 bulan - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/rec8OrloFXHrWoDYM?blocks=hide)
Title: Set year correctly on agenda navigation
Participants: @bangunbagustapa @Ibwedagama @naufalihsank @maulanayuseph

Fix: set year correctly on agenda navigation

---

components/Pagination/index.vue

- Currently, the `Pagination` component's popover has a lower `z-index` value than the `NewsVideoHeadline` component, this causes problems when user tries to change the _item per page_ and _page_ values ​​using the _select dropdown_. they will accidentally click on the `NewsVideoHeadline` component and open a new tab.
- To fix this issue we need to add a higher `z-index` value on `Pagination` popover
title: Fix pagination popover z-index
participants: @Ibwedagama @maruf12 @bangunbagustapa @naufalihsank @yoslie

Fix Pagination Popover Z-Index

---

components/News/Item/index.vue
components/News/List/index.vue
test/unit/NewsItem.spec.js

- remove click events on `NewsItem` component and replace it with `Link` component
- remove `emit on click` test case on `NewsItem` test file
title: Remove click event on NewsItem component
participants: @Ibwedagama @maulanayuseph @adzharamrullah @bangunbagustapa @yoslie

Fix: remove click event on NewsItem component

---

components/Search/index.vue

- change items per page options from `5, 10, 15` to `6, 9, 15`
- fix items per page bug when the user changes page
title: Change items per page options on pagination
participants: @Ibwedagama @maruf12 @bangunbagustapa @naufalihsank @yoslie

Fix: change items per page options on pagination

---

components/Search/List/index.vue
components/Search/index.vue

- add `maxLength` props on `SearchItemSkeleton` component
- adjust prop-binding on `Search` component
title: Fix search item skeletons render loop
participants: @Ibwedagama @maruf12 @adzharamrullah @bangunbagustapa

Fix: Search item skeletons loop

---

components/Agenda/Navigation/index.vue

- Fix the navigation show the wrong month and year in the navigation
- [T28 - Kalender Bulanan](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recMoYGn2FF8Bw9DE?blocks=hide)
Title: Fix agenda navigation month and year
Participants: @bangunbagustapa @maruf12 @Ibwedagama @naufalihsank

fix(agenda): fix date displayed in the navigation

---

components/News/List/Header/index.vue
components/News/List/index.vue
components/NewsDetail/index.vue

- [T30 - Sticky -Berita Terkait - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/rec4LzokIcYmXEeIS?blocks=hide)
- [S19A6 - Sidebar 
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recj2W1SWmiVoqyJK?blocks=hide)
- minor refactor and fix styling on `NewsListHeader` component
- add ability to adjust `max-height` and scroll on `NewsList` component
- adjust height of **related news** section on news detail page based on client _viewport_
**Before**
**After**
title: Improve related news section
participants: @Ibwedagama @maruf12 @maulanayuseph @yoslie @bangunbagustapa

Improve: related news section

---

nuxt.config.js

Apparently, Nuxt didn't set up a _cache policy_ for images stored in the `static` folder because this directory is not processed by `webpack`. The problem is all of the images and icons used on **Portal Jabar** are stored in `static` folder, this causes the app to re-download the images and icons every time users refresh the page. 
To solve this problem we can use one of the following solutions:
1. move all images and icons to `assets` folder
2. set up a cache policy on `nuxt.config.js`
the quick fix to this problem is to use the second option, which is to set up a cache policy on `static` directory.
ref:
[Nuxt.js Docs on Static Directory](https://nuxtjs.org/docs/directory-structure/static/)
[How do I solve the nuxt static image caching …

Setup cache for static directory

---

components/FeaturedProgram/Filter/index.vue
components/Pagination/index.vue
components/Search/Toolbar/index.vue

There is a CSS conflict when I try to override `jds-design-system` component styling. To avoid these conflicts, I try to add a class to each component that wraps `jds-design-system` components to improve specificity.
- add class to `Pagination` component
- add class to `FeaturedProgramFilter` component
- add class to `SearchToolbar` component
title: fix CSS class conflict
participants: @Ibwedagama @maulanayuseph @maruf12 @adzharamrullah @yoslie

Fix css class conflict

---

components/LatestNews/Preview/index.vue
components/LatestNews/Tab/index.vue
components/News/index.vue
components/NewsDetail/index.vue

- [T98 - Berita - Arsipkan berita - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/rec6yDO4I9Rwmgr28?blocks=hide)
- news with `DRAFT` status still showing on the public website
- to fix this issue we need to filter the news with `PUBLISHED` status
title: refactor show news data with status published
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @naufalihsank @yoslie

Refactor: show news data with status published

---

components/NewsDetail/Tags/index.vue
components/NewsDetail/index.vue

- change tag name property on `NewsDetailTag` component
- hide tags section when the tags is empty
title: fix tag property name
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @naufalihsank @yoslie

fix: fix tag property name

---

components/LatestNews/Preview/index.vue
components/LatestNews/Tab/index.vue
components/News/index.vue
components/NewsDetail/index.vue

- add `sort_by` and `sort_order` params on every network request to `/news` endpoint
title: fix news sort by and sort order
participants: @Ibwedagama

fix: news sort by and sort order

---

components/NewsDetail/Tags/index.vue

- [S43A8 - Link tag pada berita tidak clickable](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recc7tpHAKJBIHxk1?blocks=hide)
Title: refactor(news detail): make tags not clickable
Participants: @bangunbagustapa @naufalihsank @Ibwedagama @maulanayuseph @agunghide

refactor(news detail): make tags not clickable

---

pages/tentang-jawa-barat/index/daftar-kabupaten-kota.vue

`<a></a>` tag fails to open link correctly if the `href` attribute don't contain `http` or `https`
- fix (kabupaten-kota): fix broken website link
title: fix broken website link
participants: @Ibwedagama @agunghide @bangunbagustapa @yoslie @doohanas

fix (kabupaten-kota): fix broken website link

---

components/Profile/JabarAchievements/Item/index.vue
components/Profile/JabarAchievements/index.vue

- [T191 - Daftar prestasi jabar - Menampilkan empty state pada saat mengubah pilihan kategori di halaman ke-2 atau seterusnya  - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/rec3RdLtDez8MfVWO?blocks=hide)
- [T201 - Kategori di halaman prestasi jabar masih clickable - FE
](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recIjAPp24ajJHZwq?blocks=hide)
- fix (jabar-achievements): fix pagination bug when category filter change
- refactor (jabar-achievements): remove link on item's category

fix (jabar-achievements): fix pagination bug when category filter change

---

nuxt.config.js

Disabling zoom with meta `user-scalable : no` or `maximum-scale : 1` is considered to be bad practice and affects the Accessibility score
[ref](https://web.dev/meta-viewport/?utm_source=lighthouse&utm_medium=devtools)
title: remove meta maximum-scale to improve accessibility
participants: @Ibwedagama @maruf12 @agunghide @naufalihsank @yoslie @doohanas

fix (nuxt.config): remove meta maximum-scale to improve accessibility

---

components/Search/index.vue

- [T248 - Tombol lihat semua tidak aktif (hilang) ketika hasil pencarian lainnya <=3](https://app.clickup.com/t/2nfy973)
- refactor (search): hide more button if search data less than 3
title: conditionally hide more search results button

refactor (search): conditionally hide more search results button
