.dockerignore
Dockerfile
captain-definition

- Add `Dockerfile` file
- Add `.dockerignore` file
- Add `captain-definition` file

Setup staging server

---

.github/workflows/code-linting.yml

- Add GitHub Actions workflow for code linting

Add code linting workflow

---

static/data/menus.js

- Change url in quick link menu data
- [S7A1 - Card Layanan Jawa Barat](https://airtable.com/tblgZxVWYO3IAetyq/viw8lVCp7tu3D4tR6/rectA5cmJlTSv9c9D?blocks=hide)

Change url for lapor menu in quick link section

---

components/MostPopularServices/index.vue
pages/index.vue
static/data/menus.js

- Add most popular services section
- [S3A1 - Section untuk wargi](https://airtable.com/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recsNbwKZKhF6NUbY?blocks=hide)
- [S3A2 - Section untuk usaha](https://airtable.com/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recHsiQUV6Ryj15KD?blocks=hide)
- [S3A3 - Section untuk Wisatawan](https://airtable.com/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec74dO7MjMFvmxYh?blocks=hide)

Add most popular services section

---

pages/informasi-dan-berita/berita/_slug/index.vue

- Add empty page for news detail to prevent error

Add empty page for news detail

---

assets/css/main.css
components/Agenda/Item/index.vue
components/Agenda/List/index.vue
components/Agenda/index.vue
components/InformationAndNews/index.vue
components/News/Preview/Item/index.vue
package-lock.json
package.json
pages/informasi-dan-berita/agenda-jabar/index.vue
utils/date.js

- Change format date function utils to be more flexible
- Adjustment for styling and method
- Add agenda widget

Add agenda widget

---

components/Agenda/Item/index.vue
components/Agenda/index.vue
utils/date.js

- Fix date background in agenda not set for next month
- Add date iso format utils

Fix date background in agenda not set for next month

---

components/Hero/index.vue
components/Search/Input/index.vue
components/Search/Suggestion/index.vue
components/Search/index.vue
nuxt.config.js
package.json
pages/pencarian/index.vue

- Add search suggestions
- Change loading color
- [S2A3 - Search](https://airtable.com/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recNecvVrzycvOgMx?blocks=hide)

Add search suggestions

---

components/Button/index.vue
components/FeaturedProgram/index.vue
pages/tentang-jawa-barat/program-unggulan.vue

- Featured program section redesign
- [S4A1 - Program Unggulan Jawa Barat](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rectvPALUmIiM46wn?blocks=hide)
Before
After

Featured program section redesign

---

components/QuickLink/index.vue
static/data/menus.js

- Redesign quick link section
Before
After

Redesign quick link section

---

components/Hero/Widget/SocialMedia/index.vue
components/Hero/index.vue

- Add widget for social media
- [S2A5 - Sosial media](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recbDpFXUXlMRaCfA?blocks=hide)
The social media data will be moved into a seperate file on the next pull request since it is also used in the different component.
Title: Add social media widget
Participants: @bangunbagustapa @adzharamrullah @maulanayuseph @yoslie @maruf_harsono ​@ArifWicakSon @adrianpdm

Add social media widget

---

components/LatestNews/Preview/index.vue
components/LatestNews/Tab/Item/Skeleton/index.vue

- Fix height
- Set duration to default (3 seconds)

Fix latest news section

---

components/Agenda/List/Item/index.vue
components/Agenda/List/index.vue

Fix date props in agenda

---

components/Feedback/index.vue
components/Modal/index.vue

- Remove close button on base modal
- [T1 - Button x di setiap pop up di hilangkan - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/rec9egsNb2zPthqqE?blocks=hide)

Remove close button on base modal

---

components/Carousel/index.vue
components/LatestNews/Preview/index.vue

- Add pause on hover in carousel
- Make total of images dynamic
- [T4 - Jumlah Berita di Carousel Berita dibuat Dinamis - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/rec5zZcRoPjhLSDlZ?blocks=hide)
- [T7 - Carousel Berita - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recpC8XfJPd5eqltL?blocks=hide)

Fix carousel

---

components/Feedback/index.vue

- Clear state on close feedback form
- Trim whitespace on form input
- [T3 - Halaman Input Feeback/Umpan Balik Ter-Refresh Ulang - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recQSXb9XlO4YNaYj?blocks=hide)
- [T8 - Feedback/Umpan balik  - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recS3mLnPMREo4sMK?blocks=hide)

Fix feedback form

---

components/Breadcrumb/index.vue
components/Jumbotron/index.vue

- Fix jumbotron styling
- Change replace method in breadcrumb component

Fix jumbotron styling

---

components/Agenda/List/index.vue
components/Agenda/index.vue
components/AgendaWidget/List/Item/Skeleton/index.vue
components/AgendaWidget/List/Item/index.vue
components/AgendaWidget/List/index.vue
components/AgendaWidget/index.vue
utils/date.js

- Improve agenda widget so it can be reusable
- Add agenda list
title: Peer code review add agenda jabar list to the main page
participants: @Ibwedagama @ihsannaufalk @adzharamrullah @maulanayuseph @yoslie

Add agenda list to agenda main page

---

nuxt.config.js

There's an issue with fullcalendar implementation of css which cause build failure.
Title: Add postcss plugins in build configuration to solve full calendar issue in staging
Participants: @bangunbagustapa @Ibwedagama @adzharamrullah @maulanayuseph @Arif9878

Fix: add postcss plugins in build configuration for full calendar

---

components/AgendaWidget/Slider/index.vue

- Change styling logic for selected item
Before
After

Fix: change styling for selected item to be the same as styling for current date

---

components/AboutJabar/FeaturedProgram/index.vue
components/Agenda/index.vue
components/Base/Container/index.vue
components/FeaturedProgram/index.vue
components/Footer/index.vue
components/Header/Menu/Item/index.vue
components/Header/index.vue
components/Hero/index.vue
components/Jumbotron/index.vue
components/MostPopularServices/index.vue
components/QuickLink/index.vue
pages/index.vue

- Add base container component
- Replace manually styled container with base container component
Title: Add base container component
Participants: @bangunbagustapa @Ibwedagama @adzharamrullah @yoslie @Arif9878

Feat: add base container component

---

components/Agenda/List/index.vue
components/AgendaWidget/List/index.vue
components/AgendaWidget/Slider/index.vue
components/AgendaWidget/index.vue

- Move fetching method to client side to fix issues in server side rendering
- Hide `Lihat Semua Agenda` button if there's no data
- Add more logic for last slider to fix the navigation icon on slider
- [T5 - List Agenda Jabar - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recOU4lBWekjiQb9B?blocks=hide)
- [T12 - Terdapat issue saat pertama kali load timeline agenda - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recciezVEQOG6K5wo?blocks=hide)
Title: Fix issue on agenda widget component
Participants: @bangunbagustapa @yoslie @maulanayuseph @naufalihsank @Ibwedagama @adzharamrullah @Arif9878

Fix: agenda widget

---

components/Agenda/Calendar/index.vue
components/Agenda/List/Header/index.vue
components/Agenda/List/index.vue
components/Agenda/Navigation/index.vue
components/Agenda/index.vue
components/AgendaWidget/List/index.vue
utils/date.js

- Show weekly view
- Add weekly list
- Refactor some utils function
title: Feat add weekly agenda
participants:

Feat: add weekly agenda

---

static/data/index.js

- [T20 - Link perizinan - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recFhXyVLMUiPAXzl?blocks=hide)
Title: Change link for perizinan online
Participants: @bangunbagustapa @Ibwedagama @naufalihsank @maulanayuseph @adzharamrullah

Fix: change link for perizinan online

---

components/News/Headline/index.vue
components/News/index.vue
test/unit/NewsHeadline.spec.js

[S18A7 - Headline Berita Utama](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recNR89MGBqV4v4eB?blocks=hide)
- rename `NewsHighlight` to `NewsHeadline`
- add click event on image
- fix ref name on unit test
title: Improve news headline
participants: @Ibwedagama @maulanayuseph @maruf12 @adzharamrullah @bangunbagustapa @naufalihsank

Improve: News Headline component

---

components/News/Item/index.vue
components/News/List/index.vue
components/News/index.vue

[S18A5 - List Berita Terbaru
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec0YJHbNGuF81WAr?blocks=hide)
[S18A6 - List Berita Terpopuler
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec59gKSiKr9MY8xo?blocks=hide)
- add Latest News section
- add Popular News section
- refactor `$fetch` options to handle more than one HTTP request
- fix layout styling
title: Feat Latest News and Popular News
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @naufalihsank @yoslie

Feat: Latest News and Popular News

---

components/News/Item/index.vue

- as the title says
title: minor fix news item styling
participants: @Ibwedagama @maulanayuseph @adzharamrullah @bangunbagustapa @yoslie

Add capitalize to category text on NewsItem component

---

components/News/Headline/index.vue
components/News/index.vue
test/unit/NewsHeadline.spec.js

S18A7 - Headline Berita Utama
- refactor `NewsHeadline` component
- fetch headline news data from API
- re-fetch data after 10 minutes
- minor fix on `NewsHeadline` test
title: Improve Headline News component
participants: @Ibwedagama @adzharamrullah @bangunbagustapa @naufalihsank @yoslie

Improve Headline News

---

components/Agenda/List/Header/index.vue
components/Agenda/List/index.vue
components/Agenda/Navigation/index.vue
components/Agenda/index.vue

- [S15A4 - Kalender Agenda Mingguan](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recljotaGHkaKjGWm?blocks=hide)
- Add circle sign if spesific day has events
- Fetch agenda only when navigate
Title: Add weekly agenda sign
Participants: @bangunbagustapa @adzharamrullah @naufalihsank @Ibwedagama @yoslie

Feat: weekly agenda sign

---

components/Agenda/Calendar/index.vue
components/Agenda/EmptyState/index.vue
components/AgendaWidget/List/EmptyState/index.vue
components/AgendaWidget/List/index.vue

- [T22 - Beranda - List Agenda - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recoq7Fo9AjzarOku?blocks=hide)
- Create empty state component for agenda
- Show empty state placeholder using this component
Title: Create empty state component for agenda
Participants: @bangunbagustapa @Ibwedagama @naufalihsank @yoslie @maulanayuseph

Chore: empty state component for agenda

---

components/News/List/index.vue
components/News/index.vue
components/Pagination/index.vue
package-lock.json
package.json

[S18A3 - List Berita Utama
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recyt57XgUh6o0vxq?blocks=hide)
- update `@jabardigitalservice/jds-design-system` to version `0.0.3-beta.11`
- create `Pagination` component
- add pagination feature
- fix minor styling bug
title: Pagination feature on main news section
participants: @Ibwedagama @adzharamrullah @bangunbagustapa @maulanayuseph @naufalihsank @yoslie

Feat: Main News Pagination

---

components/Agenda/Navigation/index.vue

- [T23 - Kalendar Mingguan - Range tanggal diantara 2 bulan - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/rec8OrloFXHrWoDYM?blocks=hide)
Title: Fix date range on agenda weekly view
Participants: @bangunbagustapa @naufalihsank @maulanayuseph @yoslie @Ibwedagama @maruf12

Fix date range on agenda weekly view

---

components/Agenda/Calendar/Events/index.vue
components/AgendaWidget/List/index.vue

Related to [this](https://github.com/jabardigitalservice/portal-jabar-services/pull/65) pull request, the category type no longer object on events.
Title: Change category type
Participants: @bangunbagustapa @naufalihsank @Ibwedagama @adzharamrullah @maulanayuseph @maruf12

fix: change category type

---

components/News/Video/Headline/index.vue
components/News/Video/Item/index.vue
components/News/Video/index.vue
nuxt.config.js
tailwind.config.js

[T27 - Video - Styling Video - FE
](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recOWW5AbVMXnGouo?blocks=hide)
- add `Open Sans` font
- add `author` label on `NewsVideoHeadline` and `NewsVideoItem`
- add `getAuthorName` method on `NewsVideo` component
| Before      | After |
| ----------- | ----------- |
|![Screenshot from 2021-11-10 12-07-08](https://user-images.githubusercontent.com/33661143/141053668-22bd8361-97f5-44e5-b1ba-f2999d2224d6.png) | ![Screenshot from 2021-11-10 12-07-46](https://user-images.githubusercontent.com/33661143/141053694-9b75f8f1-3c81-4c83-a620-9f5e67eb71ee.png)
| Before      | After |
| ----------- | ----------- |
| ![Screenshot from 2021-11-10 12-12-41](https://user-images.githubusercontent.com/33661143/141053917-03bc9e85-3b42-4350-8 …

Improve News Video Styling

---

components/Agenda/Calendar/Events/Detail/index.vue
components/Agenda/List/Item/index.vue
components/AgendaWidget/List/Item/index.vue
components/LatestNews/Preview/index.vue
components/LatestNews/Tab/Item/index.vue

Title: Capitalize category and author
Participants: @bangunbagustapa @adzharamrullah @maulanayuseph

Capitalize category and author

---

components/Hero/Image/index.vue
components/Hero/Widget/Feedback/index.vue
components/Hero/Widget/SocialMedia/index.vue
components/Hero/index.vue

Title: Add fix height to hero section
Participants: @bangunbagustapa @adzharamrullah @maulanayuseph @Ibwedagama

Add fix height to hero section

---

components/Hero/Widget/SocialMedia/index.vue
components/News/Header/index.vue
components/News/Headline/index.vue

- add `aria-label` attribute on link
- add `alt` attribute to image
- some accessibility issues regarding color contrast need to be discussed with the UI/UX Designer
- there are some accessibility issues with **JDS Design System** components like `jds-select` and `jds-pagination`
- `Agenda` page issues comes from `jds-select` component and color contrast (current score: 87)
- `Program Unggulan` page already has 100 score on accessibility
Homepage
| Before | After |
| ----------- | ----------- |
| ![Screenshot from 2021-11-16 11-04-06](https://user-images.githubusercontent.com/33661143/141922478-620e5516-16e3-47ec-bc16-3ed84b3529aa.png) | ![Screenshot from 2021-11-16 11-47-16](https://user-images.githubusercontent.com/33661143/141922694-52bf5195-1d42-4fe7-87b8-e432c8bb581b.png) |
News Page …

Minor Accessibility Improvements

---

components/Breadcrumb/index.vue
components/NewsDetail/Header/index.vue

- Change the last breadcrumb item to category 
- [S19A1 - Page Artikel Berita](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recpsLl6mheswjndw?blocks=hide)
Title: Change the last breadcrumb item to category
Participants: @bangunbagustapa @adzharamrullah @Ibwedagama

Change the last breadcrumb item to category

---

components/NewsDetail/index.vue

title: Fix meta description value
participants: @Ibwedagama @bangunbagustapa @maulanayuseph @yoslie

Fix: meta description value

---

components/NewsDetail/Header/index.vue

- [S21A1 - Modal Share Berita](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recbxQRuXKBA2THNw?blocks=hide)
Title: Add modal for social media share
Participants: @bangunbagustapa @Ibwedagama @naufalihsank @yoslie @maulanayuseph

Add modal for social media share

---

components/NewsDetail/index.vue

- as the title describes
title: Remove prefix on article body
participants: @Ibwedagama @naufalihsank @yoslie @bangunbagustapa

Fix: Remove prefix on article body

---

components/NewsDetail/Tags/index.vue

- fix data binding on `NewsDetailTags` component
- add `cursor-pointer` class
title: Fix news detail tags component
participants: @Ibwedagama @bangunbagustapa @naufalihsank @yoslie

Fix: News Detail Tags component

---

components/Search/Item/Skeleton/index.vue
components/Search/Item/index.vue
components/Search/List/index.vue
components/Search/index.vue
tailwind.config.js

[S17A3 - List Pencarian
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recOVcsQqekqt6Dxj?blocks=hide)
- create `SearchList` component
- create `SearchItem` and `SearchItemSkeleton` component
- adjust layout on `Search` component
- `SearchItem` component still using dummy data for demo purposes
title: Add search list and item component
participants: @Ibwedagama @bangunbagustapa @maruf12

Add Search List and Item component

---

components/Search/Toolbar/index.vue
components/Search/index.vue
static/icons/grid-view.svg
static/icons/list-view.svg

[S17A3 - List Pencarian
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recOVcsQqekqt6Dxj?blocks=hide)
[S17A1 - Halaman Pencarian
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recD8pb68h1ILMbTK?blocks=hide)
- create `SearchToolbar` component
- add some related icons
- add `SearchToolbar` component to `Search` component
title: Add Seach Toolbar component
participants: @Ibwedagama @adzharamrullah @yoslie

Add SearchToolbar component and assets

---

components/Pagination/index.vue
components/Search/Item/index.vue
components/Search/index.vue

[S17A3 - List Pencarian
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recOVcsQqekqt6Dxj?blocks=hide)
- add `max-height` to `<jds-pagination>` wrapper
- add `Pagination` component to `Search` component
- adjust layout and styling
title: Add pagination component
participants: @Ibwedagama @maulanayuseph @yoslie @bangunbagustapa

Add Pagination Component

---

components/Search/Sidebar/index.vue
components/Search/index.vue

- Add search category component
- [S17A3 - List Pencarian](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recOVcsQqekqt6Dxj?blocks=hide)
Title: Add search categories sidebar
Participants: @bangunbagustapa @Ibwedagama @adzharamrullah @yoslie

Add search categories sidebar

---

components/Input/Search/index.vue
components/Search/Bar/index.vue
components/Search/index.vue

- Improve `InputSearch` component
- Add `SearchBar` component to the page
- [S17A2 - Search/Pencarian](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recWEicwfoG5NnZCa?blocks=hide)
Title: Add search bar
Participants: @bangunbagustapa @adzharamrullah @yoslie @Ibwedagama

Add search bar

---

components/Input/Search/index.vue
components/Search/Bar/index.vue
components/Search/Item/Skeleton/index.vue
components/Search/Item/index.vue
components/Search/List/index.vue
components/Search/Toolbar/index.vue
components/Search/index.vue
static/data/index.js
tailwind.config.js

[S17A2 - Search/Pencarian
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recWEicwfoG5NnZCa?blocks=hide)
[S17A3 - List Pencarian
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recOVcsQqekqt6Dxj?blocks=hide)
- improve `SearchBar` component
- improve `SearchItem` and `SearchList` component
- add pagination functionality
- add total search result on `SearchToolbar`
title: search and pagination feature
participants: @Ibwedagama @maulanayuseph @adzharamrullah @yoslie

Feat: Search Feature and Pagination

---

components/Search/Item/index.vue

- change `Link` component with `<a>` tag
- fix link based on `domain` type
title: Fix search result link
participants: @Ibwedagama @maruf12 @bangunbagustapa @naufalihsank @yoslie

Fix: search results link

---

components/Search/Sidebar/index.vue
components/Search/index.vue

- Add filter by domain
- [S17A4 - Filter](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec8CzQRB9iCssvj8?blocks=hide)
Title: add filter by domain
Participants: @bangunbagustapa @naufalihsank @maulanayuseph @Ibwedagama @yoslie

feat(search): add filter by domain

---

components/Search/Toolbar/index.vue
components/Search/index.vue

[S17A5 - Sort
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recmPCj0U6og2Vzlc?blocks=hide)
- add event emit on `SearchToolbar` component
- adjust `Select` options value
- fetch data when `sortOrder` data changes
- set pagination page back to 1 when `sortOrder` data changes
title: Feat sort search results
participants: @Ibwedagama @maulanayuseph @adzharamrullah @bangunbagustapa @naufalihsank @yoslie

Feat: Sort search results

---

components/Search/EmptyState/index.vue
components/Search/InitialState/index.vue
components/Search/Toolbar/index.vue

- fix `SearchEmptyState` and `SearchInitialState` wrapper styling
- change label wording on `SearchToolbar` component
title: Fix styling on search page
participants: @Ibwedagama @maruf12 @adzharamrullah @bangunbagustapa @yoslie

Fix styling on search page

---

components/Hero/Search/index.vue
components/Search/Bar/index.vue

- Add a new endpoint for search suggestions
Titile: Add a new endpoint for search suggestions
Participants: @bangunbagustapa @Ibwedagama @yoslie @maulanayuseph

feat: add a new endpoint for search suggestions

---

components/Search/Item/index.vue

- add `div` wrapper to `img` tag
- add zoom on hover effect
- adjust styling
title: Improve search item component
participants: @Ibwedagama @adzharamrullah @bangunbagustapa @yoslie @maulanayuseph

Improve search item add zoom effect

---

static/data/index.js

Title: Fix pariwisata dan ekonomi kreatif url
Participants: @bangunbagustapa @maruf12 @maulanayuseph @yoslie @Ibwedagama

fix: fix pariwisata dan ekonomi kreatif url

---

components/FeaturedProgram/Detail/index.vue

**Before**
**After**
title: Improve featured program detail styling and structure
participants: @Ibwedagama @maulanayuseph @maruf12 @adzharamrullah @yoslie

Improve Featured Program Detail styling and structure

---

components/NewsDetail/Tags/index.vue
pages/berita/tags/_tag/index.vue

- as the title describes
- add `/berita/tags/_tag` page
- fix link on `NewsDetailTags` component
- add hover effect on tag
title: add tags page and fix link on tag component
participants: @Ibwedagama @maulanayuseph @adzharamrullah @bangunbagustapa @yoslie

Add tags page and fix link on tag component

---

components/FeaturedProgram/Filter/index.vue
components/FeaturedProgram/index.vue
static/data/index.js

- [S12A4 - Filter Program Unggulan
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec2Q97CjbzG52yKS?blocks=hide)
- Filter featured program based on category
- add featured program categories on `static/data`
- create `FeaturedProgramFilter` component
- add filter functionality on `FeaturedProgram` component
- adjust styling
title: Feat filter featured program
participants: @Ibwedagama @maulanayuseph @maruf12 @adzharamrullah @naufalihsank

Feat: Filter Featured Program

---

components/FeaturedProgram/Counter/index.vue
components/FeaturedProgram/Filter/index.vue
components/FeaturedProgram/Skeleton/index.vue
components/FeaturedProgram/index.vue

- fix layout shifting !important
- fix styling on `FeaturedProgramFilter` component
- fix styling on `FeaturedProgramCounter` component
- add skeleton on `FeaturedProgram` component
title: improve featured program's page styling
participants: @Ibwedagama @maulanayuseph @adzharamrullah @yoslie

Improve: Featured Program Styling

---

components/FeaturedProgram/index.vue

- change counter value from `Array.length` to `meta.total_count`
title: fix featured program counter
participants: @Ibwedagama @maulanayuseph @adzharamrullah @naufalihsank @yoslie

Fix: Featured Program Counter

---

components/FeaturedProgram/Filter/index.vue
static/data/index.js

- [T42 - Program Unggulan - Filter Kategori - FE
](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recvJ9NKaAyi92U7Y?blocks=hide)
- adjust featured program categories constant on `static/data`
- adjust filter label when no category is selected
title: refactor featured program filter
participants: @Ibwedagama @bangunbagustapa @maulanayuseph @yoslie

refactor: featured program filter

---

components/Feedback/index.vue
components/Input/Search/index.vue

- Fix wording
Title: Change wording
Participants: @bangunbagustapa @doohanas @maulanayuseph @maruf12 @Ibwedagama @yoslie

fix: wording

---

components/NewsDetail/Header/index.vue
components/NewsDetail/Skeleton/index.vue
components/NewsDetail/Tags/index.vue
components/NewsDetail/index.vue

- [T96 - Skeleton Loader - Berita (CMS dan Web Publik) - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recZBedeWjb8aQfSc?blocks=hide)
- improve styling on content (heading, blockquote, caption)
- add skeleton loader to news header and content
title: improve news detail
participants: @Ibwedagama @bangunbagustapa

improve: news detail

---

components/LatestNews/Preview/index.vue
components/LatestNews/Tab/Item/index.vue
components/LatestNews/Tab/index.vue
components/News/Header/index.vue
components/News/Headline/index.vue
components/News/index.vue
components/NewsDetail/Header/index.vue
components/NewsDetail/index.vue

- change news date from `created_at` to `published_at`
title: refactor news date data
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @naufalihsank @yoslie

refactor: news date data

---

components/Agenda/Calendar/Events/index.vue
components/Agenda/Calendar/index.vue
components/Agenda/List/Header/index.vue
components/Agenda/List/index.vue
components/AgendaWidget/List/index.vue

Title: refactor: change api endpoint
Participants: @bangunbagustapa @Ibwedagama @maulanayuseph @yoslie

refactor: change api endpoint

---

components/LatestNews/Preview/index.vue
components/LatestNews/Tab/index.vue
components/News/Header/index.vue
components/News/Headline/index.vue
components/News/index.vue
components/NewsDetail/Header/index.vue
components/NewsDetail/index.vue

- change news endpoint from `v1/news` to `v1/public/news`
- adjust params
- adjust data binding
title: refactor news endpoint
participants: @Ibwedagama @maruf12 @bangunbagustapa @naufalihsank @yoslie @doohanas

refactor: news endpoint

---

components/AgendaWidget/List/index.vue

Title: fix: bottom link on agenda widget
Participants: @bangunbagustapa @naufalihsank @Ibwedagama

fix: bottom link on agenda widget

---

components/Agenda/List/index.vue
components/AgendaWidget/List/index.vue

- [T160 - Scroll bar agenda jabar - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recz8ZBcT5IVq3eAD?blocks=hide)
Title: fix: scroll bar
Participants: @bangunbagustapa @doohanas @Ibwedagama @maruf12 @yoslie @maulanayuseph

fix: scroll bar

---

.github/workflows/portal-jabar-release-staging.yml

Create a CI job to build and push images to a private registry on push to `development` branch

config: add jobs portal-jabar-release-staging

---

.github/workflows/portal-jabar-release-staging.yml
components/News/index.vue

fix: CI jobs branch name

---

.github/workflows/portal-jabar-release-staging.yml

fix: ci jobs auth error

---

.github/workflows/portal-jabar-release-staging.yml

as described by the title
- fix (jobs): add secrets to portal-jabar-release-staging jobs
- fix (jobs): change tags name on portal-jabar-release-staging jobs
- fix (jobs): fix secrets config name
title: fix portal-jabar-release-staging jobs
participants: @Ibwedagama @agunghide @bangunbagustapa @yoslie

fix: portal-jabar-release-staging jobs

---

.github/workflows/portal-jabar-release-staging.yml
Dockerfile.dev

- create `Dockerfile.dev` for staging
- change file for `build and push` step using `Dockerfile.dev`

config: Dockerfile staging

---

components/Header/Menu/Item/index.vue
static/data/index.js

- [S1A6 - Enhancement Navigasi](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recLTPAx9zgyrSK57?blocks=hide)
- Change navigation layout structure
- Change navigation data
Title: refactor: navigation 
Projects: Portal Jabar
Participants: @bangunbagustapa @Ibwedagama @doohanas @agunghide @maulanayuseph @yoslie

refactor: navigation

---

components/Profile/Highlight/Banner/index.vue

Fix button color on hover
Title: fix: fix button color on hover
Projects: Portal Jabar
Participants: @bangunbagustapa @maulanayuseph @Ibwedagama @agunghide @naufalihsank @yoslie @doohanas

fix: fix button color on hover

---

components/News/Item/index.vue

- [T164 - Waktu di berita terkait tidak terupdate - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/reckJV728FvAFv6Jl?blocks=hide)
TItle: fix: news list date
Participants: @bangunbagustapa @maulanayuseph @Ibwedagama @agunghide @naufalihsank @yoslie @doohanas

fix: news list date

---

components/NewsDetail/Header/index.vue
components/NewsDetail/index.vue

- [T163 - Tambahkan peliput dan editor pada berita - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recYvd1YIJH0tbvM7?blocks=hide)
Title: refactor: news detail
Participants: @bangunbagustapa @adzharamrullah @maulanayuseph @yoslie @agunghide @Ibwedagama @doohanas

refactor: news detail

---

components/Profile/Highlight/Contribution/index.vue

- [S9A5 - Section Kontribusi Jabar Terhadap Negara](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recCLP1stkTUAfTIF?blocks=hide)
Title: refactor: add a new line for contribution info
Participants: @bangunbagustapa @Ibwedagama @adzharamrullah @agunghide

refactor: add a new line for contribution info

---

components/Profile/JabarAchievements/Item/Skeleton/index.vue
components/Profile/JabarAchievements/Item/index.vue
components/Profile/JabarAchievements/List/index.vue
components/Profile/JabarAchievements/Sidebar/index.vue
components/Profile/JabarAchievements/index.vue
pages/selayang-pandang/prestasi-jawa-barat/index.vue
static/data/index.js

- [S9A3 - Halaman Prestasi Jawa Barat](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rechwiCMQJpQpVJVA?blocks=hide)
- chore (static/data): add jabar-achievements-category constant
- chore (achievements): create jabar-achievements-sidebar component
- chore (achievements): create jabar-achievements-list and item component
- refactor (profile-jabar-achievements-list): add items, itemsPerPage and loading props
- feat (achievements): add jabar achievements page; fetch data from API
- refactor (achievements): add default icons; adjust styling on jabar-achievements-item component
- feat (achievements): add skeleton loader; adjust data binding
- refactor (achievements): set items count on search-toolbar
https://user-images.githubusercontent.com/33661143/167379899-c0e4c …

feat: jabar achievements page

---

components/Profile/Highlight/Achievement/index.vue
components/Profile/Highlight/ElevenPriority/index.vue

- change Copywrite on selayang pandang's page based on QA feedback
- refactor (evelen-priority): change copywrite on item
- refactor (achievements): change button copywriting
- refactor (achievements): change tag from link to span
title: refactor selayang pandang page copywriting
participants: @Ibwedagama @maulanayuseph @adzharamrullah @agunghide @bangunbagustapa @naufalihsank @yoslie @doohanas

refactor: selayang pandang copywriting

---

pages/tentang-jawa-barat/index.vue
pages/tentang-jawa-barat/index/daftar-kabupaten-kota.vue
pages/tentang-jawa-barat/index/daftar-perangkat-daerah.vue
pages/tentang-jawa-barat/index/index.vue
pages/tentang-jawa-barat/index/lambang-dan-moto.vue
pages/tentang-jawa-barat/index/pimpinan-jabar.vue
pages/tentang-jawa-barat/index/sejarah-jabar.vue
pages/tentang-jawa-barat/index/struktur-perangkat-daerah.vue
pages/tentang-jawa-barat/index/visi-misi-pemprov-jabar.vue
static/data/index.js

- [S10A1 - Navigasi Tentang Jawa Barat](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec5DMCKP9SanL3mn?blocks=hide)
Title: feat: about jabar navigation
Participants: @bangunbagustapa @naufalihsank @yoslie @doohanas @agunghide

feat: about jabar navigation

---

components/Profile/Highlight/Contribution/index.vue

- [S10A1 - Navigasi Tentang Jawa Barat](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec5DMCKP9SanL3mn?blocks=hide)
Title: refactor: jabar contribution wording
Participants: @bangunbagustapa @Ibwedagama

refactor: jabar contribution wording

---

components/Profile/Highlight/Achievement/index.vue

title: refactor change achievements data on selayang pandang
participants: @Ibwedagama @maulanayuseph @agunghide @bangunbagustapa @doohanas

refactor : change achievements data on selayang pandang

---

components/Input/Search/index.vue
components/Profile/JabarAchievements/EmptySearch/index.vue
components/Profile/JabarAchievements/List/index.vue
components/Profile/JabarAchievements/index.vue

- [S9A3 - Halaman Prestasi Jawa Barat](http://localhost:3000/selayang-pandang/prestasi-jawa-barat)
- refactor (input-search): add clear events when clear button clicked
- refactor (achievements): move fetching logic to async fetch; remove l…
- feat (achievements): add search functionality
- chore (achievements): create empty-search component
- feat (achievements): render empty-search component when result not found
- feat (achievements): filter by categories
- feat (achievements): add sort functionality
- Search Feature
https://user-images.githubusercontent.com/33661143/167583784-feed7f22-3529-4350-a247-688fcd5decd7.mov
- Empty Search Result
https://user-images.githubusercontent.com/33661143/167583879-bed2a930-7b75-4eb3-a448-b35ae3f71c54.mov
- Filter by category and Sort functionality …

feat: jabar achievements search filter

---

components/Profile/JabarAchievements/EmptySearch/index.vue

title: temporary hide recommendations section
pariticipants: @Ibwedagama @maulanayuseph @bangunbagustapa @yoslie

refactor: temporarily hide recommendations section

---

pages/tentang-jawa-barat/index.vue

- [S10A1 - Navigasi Tentang Jawa Barat](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec5DMCKP9SanL3mn?blocks=hide)
TItle: refactor: change breadcrumb items on tentang jawa barat page
Participants: @bangunbagustapa @maulanayuseph @maruf12 @Ibwedagama @agunghide @yoslie @doohanas

refactor: change breadcrumb items on tentang jawa barat page

---

components/GPRWidget/index.vue
layouts/default.vue
nuxt.config.js

as described by the title
- chore (nuxt-config): add kominfo gpr script
- feat (gpr): add GPR widget to layout component
title: feat gpr widget
participants: @Ibwedagama @maulanayuseph @agunghide @bangunbagustapa @yoslie @doohanas

feat: gpr widget

---

components/News/index.vue
static/data/index.js

change the active category on news page based on URL query params
- refactor (news): add query param when category change; fetch news based on query
- refactor (static/data): remove lainnya value from news-categories
- refactor (static/data): add link to each news category on navigationMenu constant
title: feat news link by category
participants: @Ibwedagama @maulanayuseph @agunghide @bangunbagustapa @yoslie

feat: news link by category

---

pages/tentang-jawa-barat/index/visi-misi-pemprov-jabar.vue

- [S10A2 - Visi Misi Pemprov Jabar](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recLi9IVIddJrJVnh?blocks=hide)
Title: refactor: visi wording on visi misi page
Participants: @bangunbagustapa @maruf12 @Ibwedagama @agunghide @naufalihsank @yoslie @doohanas

refactor: visi wording on visi misi page

---

components/Header/Menu/Item/index.vue
static/data/index.js

Refactor structure data on navigation
Title: refactor: navigation menu
Participants: @bangunbagustapa @yoslie @agunghide

refactor: navigation menu

---

pages/tentang-jawa-barat/index/sejarah-jabar.vue

- [S10A4 - Sejarah Jawa Barat](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recS1dCz8UjBgfXsU?blocks=hide)
https://user-images.githubusercontent.com/55199533/168718878-34902154-184e-4edd-aeaa-8ded39c133c4.mov
Title: feat: add sejarah jawa barat page
Participants: @bangunbagustapa @maruf12 @maulanayuseph

feat: add sejarah jawa barat page

---

pages/tentang-jawa-barat/index/sejarah-jabar.vue

- [S10A4 - Sejarah Jawa Barat](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recS1dCz8UjBgfXsU?blocks=hide)
TItle: fix: sejarah jawa barat text
Participants: @bangunbagustapa @maulanayuseph @agunghide @yoslie @doohanas

fix: sejarah jawa barat text

---

app/router.scrollBehavior.js

- [T172 - Footer Tentang Jawa Barat  - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/reczR2shCoALVWDiH?blocks=hide)
TItle: fix: scroll behavior
Participants: @bangunbagustapa @doohanas @agunghide @naufalihsank

fix: scroll behavior

---

components/Profile/JabarAchievements/index.vue
pages/selayang-pandang/prestasi-jawa-barat/index.vue

- [S9A3 - Halaman Prestasi Jawa Barat](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rechwiCMQJpQpVJVA?blocks=hide)
- refactor (achievement): update achiement page jumbotron subtitle
- refactor (achievements): refactor search bar placeholder
title: refactor achievement page
participants: @Ibwedagama @maulanayuseph @agunghide @bangunbagustapa @naufalihsank @yoslie @doohanas

refactor: achievement page

---

components/Profile/JabarAchievements/Sidebar/index.vue

- feat (achievements): render categories data from API
title: feat render categories data from API
participants: @Ibwedagama @bangunbagustapa @doohanas

feat (achievements): render categories data from API

---

components/GPRWidget/index.vue
components/Hero/Widget/Feedback/index.vue

[S4A2 - GPR Widget
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec8rYfZ0QS6MrMCg?blocks=hide)
- style (hero-feedback): adjust widget position
- style (gpr-widget): improve gpr widget position
https://user-images.githubusercontent.com/33661143/169244665-d8f7dd24-fa59-4654-829b-9ecdac66b7d2.mp4
title: improve GPR widget
participants: @Ibwedagama @maulanayuseph @agunghide @bangunbagustapa @yoslie

improve: gpr widget

---

components/Button/index.vue
components/Feedback/index.vue

- [S43A4 - Feedback from terpotong di resolusi xxx](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recgLQ6HxjWMT6W8w?blocks=hide)
- refactor (button): add listeners on Button component
- refactor (feedback): refactor feedback modal using base-modal; remove form tag
- refactor (feedback): remove multiple feedback modal; add dialog state
https://user-images.githubusercontent.com/33661143/169265189-8cfef614-74b3-4c60-bde5-955bdc913741.mp4
title: refactor feedback form
participants: @Ibwedagama @bangunbagustapa @agunghide @yoslie

refactor: feedback form

---

components/Search/Toolbar/index.vue
pages/tentang-jawa-barat/index/daftar-kabupaten-kota.vue

- [S10A8 - Daftar Kabupaten/Kota](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recEw5MFx4CBiBf3h?blocks=hide)
https://user-images.githubusercontent.com/55199533/169441651-19916ace-3d94-492a-9a4e-f3a407f0c5d0.mov
Title: feat: daftar kabupaten kota page
Participants: @bangunbagustapa @Ibwedagama

feat: daftar kabupaten kota page

---

components/Footer/Copyright/index.vue
components/Footer/Sitemap/index.vue
components/Footer/index.vue

- [S8A4 - Enhancement Footer
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recX7tiBahr2nrbIK?blocks=hide)
- refactor (footer): temporary hide element; refactor kotak-layanan link
- refactor (footer): change nuxt-link component with Link component
- refactor (footer): add link to footer logo
- refactor (footer): improve footer sitemap styling and structure
title: revamp footer
participants: @Ibwedagama @agunghide @bangunbagustapa @yoslie

revamp: footer

---

pages/tentang-jawa-barat/index/daftar-perangkat-daerah.vue

- [S10A7 - Daftar Perangkat Daerah](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recYAu2t0rkqVI0Hh?blocks=hide)
https://user-images.githubusercontent.com/55199533/169467389-af6e084c-e6f7-43e8-ab2e-4be7af0be323.mov
Title: feat: daftar perangkat daerah page
Participants: @bangunbagustapa @Ibwedagama @agunghide @naufalihsank

feat: daftar perangkat daerah page

---

.github/workflows/release-production.yml

feat: add release production workflows

---

components/Footer/Copyright/index.vue

- [S43A10 - Ketentuan layanan, aksesibilitas, dan kontak layanan di hide](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recH1iN67muo6Gy2s?blocks=hide)
Title: refactor(footer): temporary hide element
Participants: @bangunbagustapa @Ibwedagama @naufalihsank @agunghide

refactor(footer): temporary hide element

---

components/News/index.vue
static/data/index.js

- [S43A9 - Section Video di hide](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rectEidbrAha0nQai?blocks=hide)
- [T165 - Terdapat perbedaan kategori berita - PM, FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/rec5EWFxmBdi2XXWv?blocks=hide)
Title: revamp: news page
Participants: @bangunbagustapa @naufalihsank @Ibwedagama @agunghide @maulanayuseph

revamp: news page

---

components/Profile/JabarAchievements/Sidebar/index.vue
components/Profile/JabarAchievements/index.vue
components/Search/Toolbar/index.vue

- [S9A3 - Halaman Prestasi Jawa Barat](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rechwiCMQJpQpVJVA?blocks=hide)
- refactor (search-toolbar): add default value to sort-options; adjust styling
- refactor (jabar-achievements): change sort_by value; add sortOptions props on search-toolbar
- style (jabar-achievements-sidebar): remove capitalize class
title: refactor jabar achievements sort
participants: @Ibwedagama @naufalihsank @yoslie

refactor: jabar achievements sort

---

components/Profile/JabarAchievements/index.vue
pages/tentang-jawa-barat/index/daftar-kabupaten-kota.vue
pages/tentang-jawa-barat/index/daftar-perangkat-daerah.vue

- [S10A7 - Daftar Perangkat Daerah](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recYAu2t0rkqVI0Hh?blocks=hide)
- [S10A8 - Daftar Kabupaten/Kota](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recEw5MFx4CBiBf3h?blocks=hide)
- fix (jabar-achievements): fix pagination bug
- fix (daftar-kabupaten-kota): fix pagination bug
- fix (daftar-perangkat-daerah): fix pagination bug
title: fix pagination bug
paticipants: @Ibwedagama @maulanayuseph @agunghide @naufalihsank @yoslie @doohanas

fix: pagination bug

---

components/FeaturedProgram/index.vue

- feat (featured-program): show program detail based on url query param
https://user-images.githubusercontent.com/33661143/170179949-db7b0fb0-f659-4d5d-b2c3-067c841d3072.mov
title: feat show program detail based on URL param
participants: @Ibwedagama @maulanayuseph @agunghide @bangunbagustapa @yoslie @doohanas

feat (featured-program): show program detail based on url query param

---

components/AgendaWidget/Slider/index.vue

Title: style(agenda widget): change default hover color
Participants: @bangunbagustapa @maulanayuseph @Ibwedagama @doohanas

style(agenda widget): change default hover color

---

components/Search/Bar/index.vue
components/Search/EmptyState/index.vue
components/Search/InitialState/index.vue

- refactor (search-bar): conditional rendered suggestion based on props
- refactor (search-empty-state): conditional rendered recommendation based
- refactor (search-initial-state): conditional rendered recommendation based on props
title: refactor search related components
participants: @Ibwedagama @bangunbagustapa @yoslie

refactor: search related component

---

components/MobileViewportBlocker/index.vue

refactor (mobile-viewport-blocker): change title
title: change title on mobile viewport blocker
participants: @Ibwedagama @maulanayuseph @maruf12 @agunghide @bangunbagustapa @yoslie

refactor (mobile-viewport-blocker): change title

---

components/Footer/Sitemap/index.vue
static/data/index.js

- [S44A1 - Dashboard Publik](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recPNzqmib5gQZdRR?blocks=hide)
- [S44A2 - Menambah section dashboard publik pada footer](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recUXzSsJgGwicjX1?blocks=hide)
- Add dashboard publik menu on header
- Add dashboard publik menu on footer
Title: feat: dashboard publik
Participants: @bangunbagustapa @Ibwedagama

feat: dashboard publik

---

components/Search/Item/index.vue
components/Search/List/index.vue
components/Search/index.vue
static/data/index.js

- [S17A - Enhancement Search Not Found](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recSVu4xqou6Is6WB?blocks=hide)
- [S17A - Enhancement Search Found](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recr9pZ4GJr7bJQTa?blocks=hide)
- refactor (static/data): add featured program domain on searchDomains constant
- refactor (search-item): adjust link based on domain; adjust image
- refactor (search-list): add default value to items props
- feat (search): add search functionality
- refactor (search-item): refactor description computed property; add color to highlited text
- **Search Not Found**
https://user-images.githubusercontent.com/33661143/170927905-5e286bb7-f8be-4462-ba24-a030c329db67.mov
- **Initial Search**
- **Search Found** …

feat: revamp search functionality

---

static/data/index.js

Title: fix: navigation wording
Participants: @bangunbagustapa @Ibwedagama

fix: navigation wording

---

components/Hero/Search/index.vue

title: temporary disable suggestion feature
participants: @Ibwedagama @maulanayuseph @agunghide

refactor (hero): temporary disable suggestion feature

---

components/Hero/index.vue
static/data/index.js

- [S43A13 - Update microcopy Landing Page
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recFfqKvuGMuAqfXX?blocks=hide)
Before
After
title: update home page microscopy
participants: @Ibwedagama @maulanayuseph @maruf12 @agunghide @doohanas

refactor: update home page microcopy

---

components/Search/index.vue
components/SearchByDomain/index.vue
pages/pencarian/_domain/index.vue

- [S17A - Halaman Pencarian Lihat Semua](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recvki8DwznCKbgPn?blocks=hide)
- refactor (search): change global search url from global to lainnya
- refactor (global-search): change default pagination item and options
title: refactor global search
participants: @Ibwedagama @maulanayuseph @agunghide @doohanas

refactor: global search

---

components/Search/Item/index.vue

- style (list-item): remove line-clamp
title: refactor list item
participants: @Ibwedagama @khihadysucahyo

refactor: list item

---

pages/pencarian/index.vue

- refactor (search): update search page jumbotron subtitle

refactor: search jumbotron subtitle

---

components/NewsDetail/Share/index.vue
pages/berita/_slug/index.vue

- feat (news): add share counting functionality

feat (news): add share counting functionality

---

pages/tentang-jawa-barat/index/daftar-perangkat-daerah.vue

- refactor (perangkat-daerah): add fallback image on eror
- refactor (perangkat-daerah): hide website if data undefined

refactor: perangkat daerah

---

components/NewsDetail/Header/index.vue

fix (news-detail): fix news share on news header

fix (news-detail): fix news share on news header

---

static/data/index.js

- fix (static/data): fix popular service link

fix (static/data): fix popular service link

---

static/data/index.js

- fix (static/data): fix popular service link

Release Production v1.1.1

---

components/Hero/Search/index.vue
package-lock.json
package.json

- [T209 - Behavior menggeser tab rekomendasi pencarian populer - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recgT4qgEG2MCJrGA?blocks=hide)
- chore (packages): add swiper and vue-awesome-swiper packages
- refactor (hero-search): add swiper to popular search
https://user-images.githubusercontent.com/33661143/172299894-5ec9eceb-8936-48c6-a9ad-e4c9db84b944.mov
title: feat hero search carousel
participants: @Ibwedagama @yoslie

feat: hero search carousel

---

components/Hero/Search/index.vue
nuxt.config.js
plugins/vue-awesome-swiper.js

- fix (nuxt-config): change gpr widget script to async
- chore (plugin): add vue-awesome-swiper plugin
- fix (hero): fix swiper behavior on initial load
title: fix hero search swiper
participants: @Ibwedagama @maruf12 @adzharamrullah

fix: hero search slider

---

components/Hero/Search/index.vue
nuxt.config.js
package-lock.json
package.json
plugins/vue-awesome-swiper.js

- feat: add swiper on hero search section
title: portal jabar release production v1.1.5
participants: @Ibwedagama @adzharamrullah

Release Production v1.1.5

---

components/Profile/Highlight/Achievement/index.vue

- [T203 - Behavior menggeser card list prestasi jabar - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recOsZEebSeVNXBp5?blocks=hide)
https://user-images.githubusercontent.com/33661143/172559512-30c98b32-a7cf-4234-9496-89b0be76fafd.mov
title: add swiper to jabar achievement section
participants: @Ibwedagama @agunghide @yoslie @doohanas

refactor (selayang-pandang): add swiper to jabar achievements section

---

components/LatestNews/Preview/index.vue
components/LatestNews/Tab/index.vue

- fix (news): add try-catch block
title: hotfix server-side fetching error
participants: @Ibwedagama @yoslie

hotfix: server-side fetching error

---

components/MobileViewportBlocker/index.vue

- [T211 - wording block overlay - FE
](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recKYYjQvWK9xkPLd?blocks=hide)
title: update mobile viewport blocker copywriting
participants: @Ibwedagama @yoslie @doohanas

refactor: update mobile viewport blocker copywriting

---

components/News/Category/index.vue

- [T208 - Behavior menggeser card list kategori berita - FE
](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recvHwxwFeJSF2nGg?blocks=hide)
https://user-images.githubusercontent.com/33661143/172790383-7b7d40d3-0b95-4328-b933-0e0a733fc81c.mov
title: add swiper to news-category
participants: @Ibwedagama @naufalihsank @yoslie @doohanas

refactor: add swiper to news-category

---

components/MobileViewportBlocker/index.vue

- [S43A18 - Update konten block Overlay
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viw1Q3jVuc9sA5lmh/recekxNoBOu3D0G6f?blocks=hide)
fix: mobile viewport blocker copywriting
title: hotfix mobile viewport blocker subtitle
participants: @Ibwedagama @yoslie @doohanas

fix: mobile viewport blocker copywriting

---

pages/tentang-jawa-barat/index/pimpinan-jabar.vue

- [T204 - Behavior menggeser card list masa jabatan gubernur sebelumnya - FE
](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/rec9GglXl2pVTyyTy?blocks=hide)
- refactor (pimpinan-jabar): improve pimpinan-jabar section behavior using swiper
https://user-images.githubusercontent.com/33661143/172806990-87838b80-0b81-4d2d-93cc-778b7b9ad8b3.mov
title: improve slider on pimpinan-jabar page
participants: @Ibwedagama @maulanayuseph @yoslie @doohanas

refactor: improve slider on pimpinan-jabar page

---

components/GPRWidget/index.vue
components/Hero/Search/index.vue
components/Hero/Widget/Feedback/index.vue
components/Hero/Widget/SocialMedia/index.vue
components/Hero/index.vue
components/Input/Search/index.vue
layouts/default.vue

https://user-images.githubusercontent.com/33661143/173529871-f574d439-ce23-4f2a-8ddd-12ab47f68aa4.mov
title: feat responsive hero section
participants: @Ibwedagama

feat (hero): add responsive hero section

---

components/AgendaWidget/index.vue
components/FeaturedProgramPreview/index.vue
components/GPRWidget/index.vue
components/Hero/Search/index.vue
components/Hero/Widget/Feedback/index.vue
components/Hero/Widget/SocialMedia/index.vue
components/Hero/index.vue
components/LatestNews/Preview/index.vue
components/LatestNews/Tab/index.vue
components/LatestNews/index.vue
components/MostPopularServices/index.vue
components/QuickLink/index.vue
pages/index.vue
plugins/vue-awesome-swiper.js

- add responsive styling to Home Page
https://user-images.githubusercontent.com/33661143/173797508-100d6147-84bb-45b1-8045-9a9128c5572e.mov
https://user-images.githubusercontent.com/33661143/173797548-180ba1ec-bf80-4ca8-9182-3d12a493f4e0.mov
https://user-images.githubusercontent.com/33661143/173797878-59c98775-282d-4535-ba75-db63b605134c.mov
title: feat responsive home page
participants: @Ibwedagama @agunghide @yoslie

feat: resposive home page

---

components/Base/Modal/index.vue
components/Header/index.vue
components/News/List/index.vue
components/NewsDetail/Header/index.vue
components/NewsDetail/Share/index.vue
pages/berita/_slug/index.vue

- [S45A3 - Detail Berita](https://app.clickup.com/t/2dzftw2)
**Mobile**
https://user-images.githubusercontent.com/33661143/174776667-b9d95d49-b361-40bf-9ada-a46ea5aa785c.mov
**Tablet**
https://user-images.githubusercontent.com/33661143/174776689-c096aea0-f15d-4971-9e09-30aa18638c73.mov
title: responsive news detail page

feat: responsive news detail page

---

components/AgendaWidget/List/Item/index.vue
components/Base/Modal/index.vue
components/FeaturedProgramPreview/index.vue
components/Footer/Copyright/index.vue
components/Footer/Info/index.vue
components/Footer/Sitemap/index.vue
components/Header/Sidebar/index.vue
components/Header/index.vue
components/Hero/index.vue
components/MostPopularServices/index.vue
layouts/default.vue
pages/index.vue

- [S45A1 - Landing Page](https://app.clickup.com/t/2dzft5a)
title: improve responsive home page 
participants: @Ibwedagama @adzharamrullah @agunghide

improve: responsive home page

---

components/Breadcrumb/index.vue
components/FeaturedProgram/Counter/index.vue
components/FeaturedProgram/Detail/index.vue
components/FeaturedProgram/Filter/index.vue
components/FeaturedProgram/index.vue
components/Jumbotron/index.vue

- [S45A4 - Halaman Program Unggulan](https://app.clickup.com/t/2fd5u9z)
**Mobile**
https://user-images.githubusercontent.com/33661143/175211456-8df3726f-caf2-4ac1-883b-ebb26bd35bf4.mov
**Tablet**
https://user-images.githubusercontent.com/33661143/175211505-8f09d9d3-81e1-44df-bcdc-69c7ac2dc8c6.mov
title: responsive featured program page
participants: @Ibwedagama @agunghide @yoslie @doohanas

feat: responsive featured program page

---

components/Hero/Search/index.vue
components/Input/Search/index.vue
layouts/default.vue
pages/index.vue

- [S17A6 - Enhancement Global Search pada Landing Page
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recv1WnpjLnPVeEPs?blocks=hide)
**Mobile**
https://user-images.githubusercontent.com/33661143/175224141-9ae60cb4-9f6f-4f87-877d-ea3c53fc043d.mov
**Tablet**
https://user-images.githubusercontent.com/33661143/175224165-b0644fbe-2d85-41ee-aac3-a3229c8f3ba3.mov
title: feat search running placeholder
participants: @Ibwedagama @khihadysucahyo @rachadiannovansyah

feat: search running placeholder

---

components/Search/InitialState/index.vue
components/Search/Item/Skeleton/index.vue
components/Search/Item/index.vue
components/Search/List/index.vue
components/Search/Toolbar/index.vue
components/Search/index.vue
components/SearchByDomain/index.vue
components/Select/index.vue

- [S45A8 - Halaman Pencarian](https://app.clickup.com/t/2fd5ukr)
**Mobile**
https://user-images.githubusercontent.com/33661143/175496686-b9dacab6-ca25-41e3-8711-5c3628d4b6cc.mp4
**Tablet**
https://user-images.githubusercontent.com/33661143/175496703-e3d83b46-0e29-429c-b322-6698caeb86a0.mp4
cc @jabardigitalservice/jds-frontend 
title: feat responsive global search page

feat: responsive global search page

---

components/Carousel/index.vue
components/FeaturedProgram/Detail/index.vue
components/Header/Sidebar/index.vue
components/Header/index.vue
components/LatestNews/Preview/index.vue
components/News/Header/index.vue
components/NewsDetail/Share/index.vue

- [S45A2 - Page Berita](https://app.clickup.com/t/2dzfttm)
- [S45A1 - Landing Page](https://app.clickup.com/t/2dzft5a)
- [S45A3 - Detail Berita](https://app.clickup.com/t/2dzftw2)
**BEFORE**
https://user-images.githubusercontent.com/33661143/175859149-3b6f477f-6f76-40eb-af35-8602589796da.mov
**AFTER**
https://user-images.githubusercontent.com/33661143/175859158-27669f9c-6836-4aaf-8a8f-9526af4f8223.mov
title: fix style bug safari mobile
participants: @Ibwedagama @maruf12 @agunghide @yoslie @doohanas

fix: style bug safari mobile

---

components/Breadcrumb/index.vue
pages/tentang-jawa-barat/index.vue
pages/tentang-jawa-barat/index/visi-misi-pemprov-jabar.vue

- [S45A6 - Tentang Jawa Barat](https://app.clickup.com/t/2fd5ujb)
**Mobile**
https://user-images.githubusercontent.com/33661143/176128542-9cf0a9e0-3338-47d3-90a6-77cfde57d53f.mov
**Tablet**
https://user-images.githubusercontent.com/33661143/176128562-f0f3ed75-404f-42e2-ae7c-3a16b4c179fe.mov
**Dekstop**
https://user-images.githubusercontent.com/33661143/176128581-f771d9bc-9393-4e83-a8f6-6d457b864ef9.mov
title: feat responsive tentang jawa barat page
participants: @Ibwedagama @agunghide

feat: responsive tentang jawa barat page

---

components/Search/Toolbar/index.vue
pages/tentang-jawa-barat/index/daftar-kabupaten-kota.vue
pages/tentang-jawa-barat/index/daftar-perangkat-daerah.vue
pages/tentang-jawa-barat/index/pimpinan-jabar.vue
pages/tentang-jawa-barat/index/struktur-perangkat-daerah.vue

- [S45A6 - Tentang Jawa Barat](https://app.clickup.com/t/2fd5ujb)
**Mobile**
https://user-images.githubusercontent.com/33661143/176640224-ac1088d8-52dd-4db4-a9e7-cf133d2ec657.mov
**Tablet**
https://user-images.githubusercontent.com/33661143/176640255-8deb7038-b301-4668-ae85-ff417355a0c3.mov
title: improve responsive tentang jabar page

improve: responsive tentang jabar page

---

components/LatestNews/Preview/index.vue
components/Search/Item/index.vue
pages/berita/_slug/index.vue

- [T244 - Waktu published berita](https://app.clickup.com/t/2hxdm2w)
title: fix news date property from created_at to published_at
participants: @Ibwedagama @maulanayuseph @maruf12 @agunghide @naufalihsank @doohanas

fix (news): change date property from created_at to published_at

---

components/AgendaWidget/index.vue

- [T243 - EYD Home page agenda](https://app.clickup.com/t/2hxdj24)
title: fix component header copywrite
participants: @Ibwedagama @agunghide @yoslie

refactor (agenda-widget-list): fix component header copywrite

---

components/Search/Item/index.vue

as described by the title
title: add a condition to render search results date
participants: @Ibwedagama @maruf12 @maulanayuseph @agunghide @doohanas @naufalihsank @yoslie

fix (search-item): add a condition to render search results date

---

components/Agenda/EmptyState/index.vue
components/Agenda/List/Header/index.vue
components/Agenda/List/Item/index.vue
components/Agenda/List/index.vue
components/Agenda/Navigation/index.vue
components/Agenda/index.vue

- [S45A5 - Agenda Jawa Barat](https://app.clickup.com/t/2fd5ub5)
**Mobile**
https://user-images.githubusercontent.com/33661143/178447948-ab4b6924-7b1b-4a7a-a3e3-6c9a34c5e5aa.mov
**Tablet**
https://user-images.githubusercontent.com/33661143/178447962-1ebadb57-189f-4921-bc55-64b2124076eb.mov
title: feat responsive agenda page

feat: responsive agenda page

---

components/FeaturedProgram/Item/index.vue
components/News/Headline/index.vue
components/News/Item/index.vue
components/Search/Item/index.vue

Add lazy load image on search, news, and featured program page
title: improvement lazy load image
participants: @Ibwedagama @maulanayuseph @maruf12 @agunghide @naufalihsank @yoslie @doohanas

improvement: lazy load image

---

components/Maintenance/index.vue
layouts/error.vue

- fix padding on Maintenance page
- fix padding on Error page
title: improve maintenance page style
participants: @Ibwedagama @maruf12 @agunghide @doohanas

improve: maintenance page style

---

components/Base/Container/index.vue

- [T228 - Lebar Konten  - FE
](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recMNV0zL80qvA240?blocks=hide)
- add max-width 1280px
- remove padding-x on big screen
title: Fix base container width and padding
participants: @Ibwedagama @maulanayuseph @maruf12 @adzharamrullah @agunghide @yoslie @doohanas

fix: base container width and padding

---

components/Search/index.vue

- [T202 - Tombol lihat semua tidak aktif ketika berita/layanan publik hasil pencarian <=3 - FE
](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recJ8bdwggvzAo8UA?blocks=hide)
- hide show more button if data length is less than or equal to 3
title: improvement conditionally show search more button
participants: @Ibwedagama @maulanayuseph @maruf12 @adzharamrullah @agunghide @yoslie @doohanas

improvement: conditionally show search more button

---

pages/tentang-jawa-barat/index.vue

As described by the title
- fix (about-jabar): fix active menu on route change
https://user-images.githubusercontent.com/33661143/179939475-8f50c34b-2db1-4fef-aeec-2de0ef1edb8c.mov
title: fix set active menu on route changes
participants: @Ibwedagama @maulanayuseph @agunghide

fix (about-jabar): set active menu on route changes

---

pages/tentang-jawa-barat/index/daftar-kabupaten-kota.vue
pages/tentang-jawa-barat/index/daftar-perangkat-daerah.vue
pages/tentang-jawa-barat/index/lambang-dan-moto.vue
pages/tentang-jawa-barat/index/pimpinan-jabar.vue
pages/tentang-jawa-barat/index/sejarah-jabar.vue
pages/tentang-jawa-barat/index/struktur-perangkat-daerah.vue
pages/tentang-jawa-barat/index/visi-misi-pemprov-jabar.vue

title: change title line-height on mobile device
participants : @Ibwedagama @maulanayuseph @agunghide @yoslie @doohanas

style (tentang-jabar): change title line-height on mobile device

---

components/Profile/Highlight/Achievement/index.vue

title: Change selayang pandang button copyrwite
participants: @Ibwedagama @maulanayuseph @agunghide @yoslie @doohanas

refactor (selayang-pandang): change button copywrite

---

components/Footer/index.vue
components/Header/Menu/Item/index.vue
components/Header/Navigation/index.vue
layouts/default.vue
static/data/index.js

- [Implementasi Google Analytics - Product Metric - Header & Footer](https://app.clickup.com/t/2q90h0p)
- chore (GPR): remove comment on GPR widget
- feat (header): track events on navigation item clicked
- feat (header): track event on header logo clicked
- feat (footer): track event on footer logo clicked
title: feat track events on header and footer
participants: @Ibwedagama @maruf12 @agunghide @yoslie @doohanas

feat: track events on header and footer

---

components/Feedback/index.vue
components/GPRWidget/index.vue
components/Hero/Widget/Feedback/index.vue

- [S46A2 - Update Microcopy Fitur Survey](https://app.clickup.com/t/2qevw05)
- refactor (feedback): refactor form data; adjust styling
- style (widget/feedback): change button text; adjust styling
- style (gpr): adjust top position
**Dekstop**
https://user-images.githubusercontent.com/33661143/182614019-76a78208-6240-40db-92a0-d908be5488e6.mov
**Tablet**
https://user-images.githubusercontent.com/33661143/182606064-b685615b-8398-41df-be15-83b30a19cf7e.mov
**Phone**
https://user-images.githubusercontent.com/33661143/182606088-7763f80a-4624-47a6-83ab-8190c3e7c7b9.mov
title: refactor survey form
participants: @Ibwedagama @agunghide @naufalihsank @yoslie @doohanas

refactor: survey form

---

components/FeaturedProgramPreview/index.vue
components/Feedback/index.vue
components/GPRWidget/index.vue
components/Hero/Widget/Feedback/index.vue
static/data/index.js

title: Release Portal Jabar Web v1.4.0
participants: @Ibwedagama @agunghide @yoslie

Release Portal Jabar Web v1.4.0

---

components/Hero/Search/index.vue
components/Hero/Widget/Feedback/index.vue
components/Hero/Widget/SocialMedia/index.vue
components/Search/index.vue

- [Implementasi Google Analytics - Product Metric - Home Page](https://app.clickup.com/t/2q90h3m)
- feat (homepage): track search events and search results on homepage
- feat (homepage): track popular search items event click
- feat (hero): track social media click event
- feat (hero): track feedback button click event
title: feat track hero section
participants: @Ibwedagama @agunghide @yoslie

feat: track hero section

---

static/data/index.js
static/icons/navigation/covid19.svg
static/icons/navigation/industri.svg

- [S46A5 - Update link info harga pangan](https://app.clickup.com/t/2tyz3b4)
- [S46A6 - Update link section Dashboard Publik](https://app.clickup.com/t/2u4k6vz)
title: release portal jabar web v1.6.0
participants: @Ibwedagama @maulanayuseph @doohanas @naufalihsank @yoslie

Release Portal Jabar Web

---

components/Base/VideoPlayer/index.vue
components/Profile/Highlight/Banner/index.vue

- [S46A3 - Embed link video profil jawa barat](https://app.clickup.com/t/2qevxxx)
**Mobile**
**Tablet**
**Desktop**
title: West Java Profile Video
participants: @naufalihsank @Ibwedagama @agunghide

West Java Profile Video

---

components/Profile/Highlight/Banner/index.vue

title: West Java Profile Video
participants: @naufalihsank @Ibwedagama @doohanas @maulanayuseph @maruf12 @agunghide @yoslie

fix microcopy section banner

---

components/Base/VideoPlayer/index.vue
components/NewsDetail/Header/index.vue
components/Profile/Highlight/Banner/index.vue
pages/berita/_slug/index.vue

- [T261 - Counter bagikan berita tidak berjalan](https://app.clickup.com/t/2vr1xrv)
- [S46A3 - Embed link video profil jawa barat](https://app.clickup.com/t/2qevxxx)
title: Fix News Views Counter
participants: @naufalihsank @Ibwedagama

Fix News Views Counter

---

components/MostPopularServices/index.vue
static/data/index.js

title: hide some contents and change PIRT link
participants: @naufalihsank @Ibwedagama

hide some popular services contents and change PIRT link

---

components/MostPopularServices/index.vue

title: fix popular services section row gap
participants: @naufalihsank @Ibwedagama

fix: fix popular services section row gap

---

components/Base/VideoPlayer/index.vue

**Mobile**
**Tablet**
**Desktop**
title: video player container improvement
participants: @naufalihsank @maulanayuseph @Ibwedagama @agunghide @yoslie @doohanas

feat: video player container improvement

---

pages/tentang-jawa-barat/index/daftar-perangkat-daerah.vue

- [S10A9 - Enhance konten daftar perangkat daerah](https://app.clickup.com/t/2xbg778)
**Mobile**
**Tablet**
**Desktop**
title: revamp perangkat daerah buttons
participants: @naufalihsank @maulanayuseph @maruf12 @agunghide @yoslie

feat: revamp perangkat daerah buttons

---

static/data/index.js

- [S1A9 - Add submenu perizinan](https://app.clickup.com/t/2xbg7q3)
- [S1A11 - Add submenu LPSE](https://app.clickup.com/t/2xwnvab)
title: change LPSE link and perizinan microcopy
participants: @naufalihsank @maulanayuseph @agunghide @yoslie @doohanas

fix: change LPSE link and perizinan microcopy

---

components/LatestNews/Tab/index.vue
pages/tentang-jawa-barat/index/daftar-perangkat-daerah.vue

- [S20A6 - Update logic Berita Highlight dan Terpopuler](https://app.clickup.com/t/2xww3xv)
- [S10A9 - Enhance konten daftar perangkat daerah](https://app.clickup.com/t/2xbg778)
title: List Perangkat Daerah and News Improvements
participants: @naufalihsank @doohanas @maulanayuseph @yoslie

List Perangkat Daerah and News Improvements

---

components/Search/Toolbar/index.vue

- [T264 - Hide fitur sorting di global search](https://app.clickup.com/t/2ydy0dp)
title: temporary hide sort dropdown
participants: @naufalihsank @agunghide @doohanas

refactor: temporary hide sort dropdown

---

components/AgendaWidget/List/Item/index.vue
components/Footer/Sitemap/index.vue
components/News/Header/index.vue
components/News/index.vue
components/Profile/JabarAchievements/MobileToolbar/Category/index.vue
components/Profile/JabarAchievements/Sidebar/index.vue
static/data/index.js

- feat: add gtag click footer sitemap for large screen
- feat: add gtag click menu ppid
- fix: gtag click agenda
- fix: naming gtag event category filter awards
- fix: gtag click related news on "baca selengkapnya"
- fix: gtag page view news
title: fix: Custom event product metric
participants: @adzharamrullah

fix: Custom event product metric

---

components/News/index.vue

- [S20A6 - Update logic Berita Highlight dan Terpopuler](https://app.clickup.com/t/2xww3xv)
title: only show previous week popular news
participants: @naufalihsank @Ibwedagama @yoslie @doohanas

feat (news): only show previous week popular news

---

pages/tentang-jawa-barat/index/pimpinan-jabar.vue

- [S10A11 - Revisi Minor Detail Profil Gubernur](https://app.clickup.com/t/301d117)
title: fix about microcopy
participants: @naufalihsank @maruf12 @doohanas

fix (pimpinan-jabar): fix about microcopy

---

pages/tentang-jawa-barat/index/pimpinan-jabar.vue

- fix (pimpinan-jabar): fix about microcopy
title: portal jabar web release v1.12.0
participants: @naufalihsank @Ibwedagama

Portal Jabar Web Release v1.12.0

---

components/AgendaWidget/List/index.vue
components/AgendaWidget/index.vue

- [T269 - Responsive section agenda](https://app.clickup.com/t/2zg7gz8)
title:set infinite scroll to event list
participants: @naufalihsank @maruf12 @Ibwedagama

feat (agenda-widget): set infinite scroll to event list

---

components/Base/ListCounter/index.vue
components/Breadcrumb/index.vue
components/Input/Search/index.vue
components/Layanan/List/Item/index.vue
components/Layanan/List/index.vue
pages/layanan/kependudukan-dan-tempat-tinggal/index.vue
static/data/index.js

- [S47A1 - View List Layanan Kependudukan dan Tempat Tinggal](https://app.clickup.com/t/2jzqfx0)
**Mobile**
**Tablet**
**Desktop**
title: Page Kependudukan dan Tempat Tinggal
participants: @naufalihsank @Ibwedagama @maulanayuseph @agunghide @yoslie @doohanas

Page Kependudukan dan Tempat Tinggal

---

components/Base/EmptyState/index.vue
components/Layanan/List/index.vue
pages/layanan/kependudukan-dan-tempat-tinggal/_slug/index.vue
pages/layanan/kependudukan-dan-tempat-tinggal/index.vue

- [S47A1 - View List Layanan Kependudukan dan Tempat Tinggal](https://app.clickup.com/t/2jzqfx0)
- create `BaseEmptyState` component
- fix breadcrumb capitalization
title: service list empty state
participants: @naufalihsank @maulanayuseph @Ibwedagama @yoslie @doohanas

feat (kependudukan-dan-tempat-tinggal): create empty state

---

components/Layanan/Item/Media/index.vue
components/Layanan/Item/Purposes/index.vue
pages/layanan/kependudukan-dan-tempat-tinggal/_slug/index.vue

- [S47A2 - Layanan SIDATUK](https://app.clickup.com/3808590/v/b/6-175624479-2)
**Mobile**
**Tablet**
**Desktop**
title: sidatuk purposes section
participants: @naufalihsank @maulanayuseph @agunghide @doohanas

feat (sidatuk): purposes section

---

components/Layanan/Item/Facilities/index.vue
pages/layanan/kependudukan-dan-tempat-tinggal/_slug/index.vue

- [S47A2 - Layanan SIDATUK](https://app.clickup.com/t/2na0hg1)
**Mobile**
**Tablet**
**Desktop**
title: sidatuk facilities section
participants: @naufalihsank @maruf12 @Ibwedagama @agunghide @yoslie

feat (sidatuk): facilities section

---

components/Layanan/Item/Requirements/index.vue
pages/layanan/kependudukan-dan-tempat-tinggal/_slug/index.vue

- [S47A2 - Layanan SIDATUK](https://app.clickup.com/t/2na0hg1)
**Mobile**
**Tablet**
**Desktop**
title: sidatuk requirements section
participants: @naufalihsank @Ibwedagama @agunghide @doohanas

feat (sidatuk): requirements section

---

components/Layanan/Item/News/index.vue
pages/layanan/kependudukan-dan-tempat-tinggal/_slug/index.vue

- [S47A2 - Layanan SIDATUK](https://app.clickup.com/t/2na0hg1)
**Mobile**
**Tablet**
**Desktop**
title: sidatuk news section
participants: @naufalihsank @maulanayuseph @Ibwedagama @agunghide @doohanas

feat (sidatuk): news section

---

components/Layanan/Item/Media/index.vue

- [S47A2 - Layanan SIDATUK](https://app.clickup.com/t/2na0hg1)
title: fix sidatuk media section's grid layout
participants: @naufalihsank @maulanayuseph @maruf12 @Ibwedagama @agunghide @yoslie

fix (sidatuk): fix media section's grid layout

---

components/PublicService/List/Item/index.vue
components/PublicService/List/index.vue
pages/layanan/_category/_slug/index.vue
pages/layanan/_category/index.vue
static/data/index.js

- Replace `kependudukan-dan-tempat-tinggal` route with general `_category` route
- Replace `LayananList` and `LayananListItem` component with `PublicServiceList` and `PublicServiceListItem` component
title: create general category page
participants: @naufalihsank @Ibwedagama @agunghide @yoslie

refactor (public-service-list): create general category page

---

components/Sapawarga/Footer/index.vue

- Update link in footer sapawarga page 
- Change link for `ketentuan pengguna` dan `privasi` 
title: Portal Jabar Web Release v1.17.1
participants: @doohanas @Ibwedagama @yoslie

Portal Jabar Web Release v1.17.1

---

components/Campaign/index.vue
pages/index.vue

- hotfix: set fetch on the client to fix fetch popup on server
title: hotfix: set fetch on the client to fix fetch popup on server
participants: @doohanas @naufalihsank

hotfix: set fetch on client to fix fetch popup on server

---

.github/workflows/code-linting.yml
.github/workflows/release-production.yml
.github/workflows/release-staging.yml
.github/workflows/website-audit.yml

- infra: setup-new-registry & improve ci/cd
title: infra: setup-new-registry & improve ci/cd
participants: @feriahmad @Ibwedagama

infra: setup-new-registry & improve ci/cd

---

static/data/index.js

* refactor (akses-cepat): hide pengembangan ekspor link temporarily
* refactor (layanan-terpopuler): change daerah wisata jabar link
* refactor (layanan-terpopuler): hide informasi rute angkutan umum link temporarily
title: release portal jabar v1.18.6
participants: @Ibwedagama @doohanas

Release Portal Jabar Web v1.18.6

---

components/Campaign/index.vue

* refactor (popup-banner): move the assign banner value inside conditional response 200 
title: release portal jabar v1.18.7
participants: @doohanas @Ibwedagama @yoslie @marsellavaleria19

Release Portal Jabar Web v1.18.7

---

components/PublicService/Revamp/PreviewJumbotron/index.vue
layouts/preview.vue
pages/preview/layanan-publik/index.vue

- [S56A11 - Preview Data Publikasi Informasi Layanan](https://app.clickup.com/t/860rcqcq4)
title: Release Portal Jabar Frontend v1.22.0
participants: @Ibwedagama @sheilaazhara @agunghide @naufalihsank @yoslie

Release Portal Jabar v1.22.0

---

pages/layanan/_slug/index.vue

- Improve SEO meta data on public service's page
- add SEO meta data
title: improve add SEO meta data for public service page
participants: @Ibwedagama @naufalihsank @rayfajars @doohanas

improve: add SEO meta data for public service page
